language: python
python:
 - "3.6"
cache: pip
services:
 - postgresql
install:
 - pip install -r requirements.txt
before_script:
 - cp env.example .env
 - psql -c 'create database test_db;' -U postgres
script:
  - python3 test.py
  - pytest test.py -v --cov=app/app.py
after_script:
 - coveralls
after_success:
 - coveralls
