language: python
python:
 - "3.6"
cache: pip
services:
 - postgresql
install:
 - pip install -r requirements.txt
before_script:
 - cp env.example .env
 - psql -c 'create database test_db;' -U postgres
script:
  - python3 test.py
  - python test.py --cov=app/app.py -v 
after_script:
 - coveralls
 - codeclimate-test-reporter
after_success:
 - coveralls
