env:
  global:
    - CC_TEST_REPORTER_ID=c74ae50767ce5179663f4c28ea737e2959ceffaa457252c86f1e7efbfb54fec1
language: python
python:
  - "3.6"
    # command to install dependencies
install:
  - pip3 install -r requirements.txt
    # command to run tests
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - python test.py
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


